"""added Game, Player, Round models

Revision ID: 0c31a2d13027
Revises: 9bf86cd4949c
Create Date: 2023-02-24 17:23:19.841754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c31a2d13027'
down_revision = '9bf86cd4949c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
