"""answering_player is varchar4

Revision ID: 134d814ff42e
Revises: e06ab1e55ea1
Create Date: 2023-02-26 23:22:38.834705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134d814ff42e'
down_revision = 'e06ab1e55ea1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('answering_player', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'answering_player')
    # ### end Alembic commands ###
