"""10/03/23 03:54 added question_chooser_player to GameModel

Revision ID: 194afff2d8c6
Revises: fbedc5bfb05b
Create Date: 2023-03-10 03:54:51.278506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194afff2d8c6'
down_revision = 'fbedc5bfb05b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('question_chooser_player', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'players', ['question_chooser_player'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'question_chooser_player')
    # ### end Alembic commands ###
