"""answering_player is varchar2

Revision ID: 2dd1b96451fd
Revises: 8687e244a75f
Create Date: 2023-02-26 23:21:56.273831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd1b96451fd'
down_revision = '8687e244a75f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
