"""added fields to Game, Player, Round models

Revision ID: 3848c8997c03
Revises: 6f21fb91e183
Create Date: 2023-02-24 19:10:24.175965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3848c8997c03'
down_revision = '6f21fb91e183'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('games', sa.Column('is_finished', sa.Boolean(), nullable=True))
    op.add_column('players', sa.Column('nickname', sa.String(length=50), nullable=False))
    op.add_column('players', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'players', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.add_column('rounds', sa.Column('count', sa.Integer(), nullable=False))
    op.add_column('rounds', sa.Column('theme_id', sa.Integer(), nullable=True))
    op.add_column('rounds', sa.Column('game_id', sa.Integer(), nullable=True))
    op.add_column('rounds', sa.Column('points', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rounds', 'games', ['game_id'], ['id'])
    op.create_foreign_key(None, 'rounds', 'themes', ['theme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rounds', type_='foreignkey')
    op.drop_constraint(None, 'rounds', type_='foreignkey')
    op.drop_column('rounds', 'points')
    op.drop_column('rounds', 'game_id')
    op.drop_column('rounds', 'theme_id')
    op.drop_column('rounds', 'count')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'game_id')
    op.drop_column('players', 'score')
    op.drop_column('players', 'nickname')
    op.drop_column('games', 'is_finished')
    op.drop_column('games', 'created_at')
    # ### end Alembic commands ###
