"""fixed mistake in previous migration Round model changed

Revision ID: 39efc567afb4
Revises: 9a795898a15e
Create Date: 2023-02-26 05:42:33.924986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39efc567afb4'
down_revision = '9a795898a15e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'game_questions', ['question_id'])
    op.add_column('rounds', sa.Column('current_question', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rounds', 'game_questions', ['current_question'], ['question_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rounds', type_='foreignkey')
    op.drop_column('rounds', 'current_question')
    op.drop_constraint(None, 'game_questions', type_='unique')
    # ### end Alembic commands ###
