"""added chat_id to Game model

Revision ID: 3bfd628b01ee
Revises: d1867b3d4339
Create Date: 2023-02-24 22:30:08.966155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bfd628b01ee'
down_revision = 'd1867b3d4339'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'games', ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='unique')
    op.drop_column('games', 'chat_id')
    # ### end Alembic commands ###
