"""removed theme Foreighn key  from GameQuestions

Revision ID: 5cc45d80f5e7
Revises: 26506d138fff
Create Date: 2023-02-26 05:29:55.577671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc45d80f5e7'
down_revision = '26506d138fff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_questions_theme_id_fkey', 'game_questions', type_='foreignkey')
    op.drop_column('game_questions', 'theme_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_questions', sa.Column('theme_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('game_questions_theme_id_fkey', 'game_questions', 'themes', ['theme_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
