"""GamePolls model was removed

Revision ID: 68f46caf7133
Revises: ece0dbe9112e
Create Date: 2023-02-28 17:01:45.043501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f46caf7133'
down_revision = 'ece0dbe9112e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_polls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_polls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('poll_id', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='game_polls_game_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='game_polls_pkey'),
    sa.UniqueConstraint('poll_id', name='game_polls_poll_id_key')
    )
    # ### end Alembic commands ###
