"""answering_player is varchar

Revision ID: 8687e244a75f
Revises: d0a32abbbbaa
Create Date: 2023-02-26 23:20:32.598805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8687e244a75f'
down_revision = 'd0a32abbbbaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
