"""Round model changed

Revision ID: 9a795898a15e
Revises: 5cc45d80f5e7
Create Date: 2023-02-26 05:37:33.066772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a795898a15e'
down_revision = '5cc45d80f5e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rounds_theme_id_fkey', 'rounds', type_='foreignkey')
    op.drop_column('rounds', 'points')
    op.drop_column('rounds', 'theme_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('theme_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rounds', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('rounds_theme_id_fkey', 'rounds', 'themes', ['theme_id'], ['id'])
    # ### end Alembic commands ###
