"""10/03/23 03:55 removed question_chooser_player to GameModel

Revision ID: b27d3f7776ab
Revises: 194afff2d8c6
Create Date: 2023-03-10 03:59:34.918644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27d3f7776ab'
down_revision = '194afff2d8c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_question_chooser_player_fkey', 'games', type_='foreignkey')
    op.drop_column('games', 'question_chooser_player')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('question_chooser_player', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('games_question_chooser_player_fkey', 'games', 'players', ['question_chooser_player'], ['id'])
    # ### end Alembic commands ###
