"""04.03.23 19:19 GameModel added default None to answering_player

Revision ID: c38779eaea25
Revises: dcf5cc1e252e
Create Date: 2023-03-04 19:20:03.090784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38779eaea25'
down_revision = 'dcf5cc1e252e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
