"""removed answering player fkey now it varchar

Revision ID: d0a32abbbbaa
Revises: 39efc567afb4
Create Date: 2023-02-26 22:51:41.721892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a32abbbbaa'
down_revision = '39efc567afb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rounds_answering_player_fkey', 'rounds', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('rounds_answering_player_fkey', 'rounds', 'players', ['answering_player'], ['id'])
    # ### end Alembic commands ###
