"""added cascade logit to game models

Revision ID: d1867b3d4339
Revises: e92860807d73
Create Date: 2023-02-24 21:37:00.730865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1867b3d4339'
down_revision = 'e92860807d73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answered_players_player_id_fkey', 'answered_players', type_='foreignkey')
    op.drop_constraint('answered_players_round_id_fkey', 'answered_players', type_='foreignkey')
    op.create_foreign_key(None, 'answered_players', 'rounds', ['round_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answered_players', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('rounds_game_id_fkey', 'rounds', type_='foreignkey')
    op.create_foreign_key(None, 'rounds', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rounds', type_='foreignkey')
    op.create_foreign_key('rounds_game_id_fkey', 'rounds', 'games', ['game_id'], ['id'])
    op.drop_constraint(None, 'answered_players', type_='foreignkey')
    op.drop_constraint(None, 'answered_players', type_='foreignkey')
    op.create_foreign_key('answered_players_round_id_fkey', 'answered_players', 'rounds', ['round_id'], ['id'])
    op.create_foreign_key('answered_players_player_id_fkey', 'answered_players', 'players', ['player_id'], ['id'])
    # ### end Alembic commands ###
