"""answering_player is varchar3

Revision ID: e06ab1e55ea1
Revises: 2dd1b96451fd
Create Date: 2023-02-26 23:22:18.151726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06ab1e55ea1'
down_revision = '2dd1b96451fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'answering_player')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('answering_player', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
