"""12-03-23-03-18 added Sequences to Qustion and Theme models

Revision ID: e5ca77d6a8e5
Revises: 90cefcb60a64
Create Date: 2023-03-12 03:19:07.837626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ca77d6a8e5'
down_revision = '90cefcb60a64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
