"""answering_player is varchar5

Revision ID: ece0dbe9112e
Revises: 134d814ff42e
Create Date: 2023-02-26 23:22:57.553179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece0dbe9112e'
down_revision = '134d814ff42e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
