"""04.03.23 20:24 GamePlayer added CASCADE None to foreign keys

Revision ID: f39513fca478
Revises: c38779eaea25
Create Date: 2023-03-04 20:24:56.796299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39513fca478'
down_revision = 'c38779eaea25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_players_game_id_fkey', 'game_players', type_='foreignkey')
    op.drop_constraint('game_players_player_id_fkey', 'game_players', type_='foreignkey')
    op.create_foreign_key(None, 'game_players', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'game_players', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_players', type_='foreignkey')
    op.drop_constraint(None, 'game_players', type_='foreignkey')
    op.create_foreign_key('game_players_player_id_fkey', 'game_players', 'players', ['player_id'], ['id'])
    op.create_foreign_key('game_players_game_id_fkey', 'game_players', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###
