"""05.03.23 03:38 added is_current field to GameQuestionsModel

Revision ID: fbedc5bfb05b
Revises: fd37c6d56650
Create Date: 2023-03-05 03:39:02.244709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbedc5bfb05b'
down_revision = 'fd37c6d56650'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_questions', sa.Column('is_current', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_questions', 'is_current')
    # ### end Alembic commands ###
