"""04.03.23 20:52 GamePlayer added UNIQUE constraint between game and player ids

Revision ID: fd37c6d56650
Revises: f39513fca478
Create Date: 2023-03-04 20:53:19.775424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd37c6d56650'
down_revision = 'f39513fca478'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_game_player', 'game_players', ['game_id', 'player_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_game_player', 'game_players', type_='unique')
    # ### end Alembic commands ###
